### ISSUE TITLE
Does Holy support RSS

### ISSUE THREAD

**Issue by Naadiyaar** [serkodev/holy#10]
i added RSS template to my blog by following [original documents](https://gohugo.io/templates/rss/) and i want to make it more visible by having it at front page, something similar to `About` page showing up. but i couldn't find anything related at [exampleSite](https://github.com/serkodev/holy/tree/master/exampleSite).

i don't know if there's a built-in functionality, or I should add this manually?

**Comment by serkodev** [comment]
Holy does not support RSS by default. I didn't delve into that, you may need to add it manually.
PRs are welcome. 😃
