### ISSUE TITLE
Editing the Coloscheme

### ISSUE THREAD

**Issue by eeriemyxi** [serkodev/holy#11]
Hi. I loved this theme and wanted to customize the color scheme.

Unfortunately, the source code is too abstract for me to understand where the color specifications are defined. Could you help this dummy out a bit? 

PS: I am not a front-end developer and don't have the slightest bit of experience in web development.

**Comment by XizumiK** [comment]
It seems you should check the file 
```
/layouts/partials/prose.html
```

Btw I'm also not familiar with front-end , so I can't provide any further help. But ChatGPT may helps.

**Comment by eeriemyxi** [comment]
Hey, thanks.
