### ISSUE TITLE
Is the theme broken?

### ISSUE THREAD

**Issue by ghost** [serkodev/holy#3]
Hello! I followed the steps in the README, wrote `hugo server -t holy` and I was greeted by this:
![image](https://user-images.githubusercontent.com/96354838/193457365-aae02112-865a-464f-974a-9b4f82f29313.png)

Sometimes the demo site also has this, even the online one. Am I doing something wrong? You should make the README more complete

**Comment by serkodev** [comment]
Hi @stalecu, holy uses [unpkg](https://unpkg.com/) for hosting some dependency library.
Can you connect to [unpkg](https://unpkg.com/) directly?
