### ISSUE TITLE
How do set the default mode to dark theme?

### ISSUE THREAD

**Issue by rysyd** [serkodev/holy#4]

**Comment by serkodev** [comment]
Holy uses [theme.js](https://github.com/serkodev/themes.js) as theme engine which works with [Master CSS](https://css.master.co/).

You may create a file in your hugo project under `./layouts/partials/head-extra.html` and add the following code
```html
<script>(window.themes || new window.Themes()).theme = 'dark';</script>
```

**Comment by rysyd** [comment]
thx a lot:)
